### ISSUE TITLE
Lesson 10. Student -Aspirant

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#10]
Приведите все в порядок - [http://www.examclouds.com/java/java-core-russian/checklist](http://www.examclouds.com/java/java-core-russian/checklist)

**Comment by milkina** [comment]
1. Метод getScholarship в Student сделайте private.
2. Добавьте метод equals в оба класса.
3. Метод print переделайте в toString().
4. Вы пишите метод main в каждом классе. Это не обязательно.

**Comment by ltolok** [comment]
Исправила.

**Comment by milkina** [comment]
Вы сделали метод Student.getScholarship private. Если вы перенесете метод main в др. класс, этот метод не вызовется. Я вам неправильно написала - хотела написать public.
В задании написано переопределить этот метод. Статический метод не переопределяется.

**Comment by ltolok** [comment]
Ок. Исправила.
