### ISSUE TITLE
Lesson 12. Одежда

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#12]
1. Переменная euroSize в Size  -  добавьте модификатор доступа.
2. Добавьте во все классы toString и equals.
3. В clotheprint используйте toString()
4. Метод clotheprint лучше переименовать в clothPrint.

**Comment by ltolok** [comment]
Исправила. Выгрузила.

**Comment by milkina** [comment]
Пункты 1,4 не выполнены.

**Comment by ltolok** [comment]
П 1, 4 выполнила.

**Comment by milkina** [comment]
Done
