### ISSUE TITLE
Lesson 13. Report

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#16]
1. Такой конструктор можно не писать. 
2.  Переменная  private Employee employee;   не нужна.

**Comment by ltolok** [comment]
Исправила.

**Comment by milkina** [comment]
Done 
но, уберите ненужную пустую строку

 @Override

    public String toString() {
        return "Employee{" +
                "fullname='" + fullname + '\'' +
                ", salary=" + salary +
                '}';
    }
