### ISSUE TITLE
Lesson 8. Person

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#2]
Добавьте еще один конструктор - Person() без параметров. И еще один объект в main, который создается с помощью этого конструктора.

**Comment by milkina** [comment]
1. Переменные String fullName; int age; должны быть private
2.  Все конструкторы и остальные методы - public.
3. После конструкторов у вас идут строки с ";". Удалите их.

**Comment by milkina** [comment]
Неотформатировано.

**Comment by ltolok** [comment]
Исправила.

**Comment by milkina** [comment]
Done
