### ISSUE TITLE
Lesson 11. AccessModifier

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#20]
1. Сделайте переменные нестатическими. 
2. Назовите их s1, s2, s3, s4.

**Comment by milkina** [comment]
1. Отформатируйте AccessModifier.
2. Modifier2, Modifier4 - вы вызываете методы и переменные  как статические. Но они же не статические.

**Comment by ltolok** [comment]
Проверьте, пжл.

**Comment by milkina** [comment]
Modifier3:

Вы можете обратиться к protected переменной из класса наследника если этот класс наследует ее:
 System.out.println(new Modifier3().s3);

**Comment by ltolok** [comment]
исправила
