### ISSUE TITLE
Lesson 11. Инструменты.

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#21]
1.  http://www.examclouds.com/java/java-core-russian/checklist

Переменные класса рекомендуется делать private.
Доступ к переменным класса осуществляется через геттеры и сеттеры.
Желательно переопределять в создаваемом классе методы toString, equals

2.  Переименуйте tools1 в tool.

 for (Tool tools1 : tools)

**Comment by ltolok** [comment]
Исправила.

**Comment by milkina** [comment]
1. Укажите модификаторы доступа для конструкторов.

**Comment by ltolok** [comment]
исправила
