### ISSUE TITLE
Lesson 14. Palindrome

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#23]
1. Вместо

           StringBuilder sb = new StringBuilder();
            sb.append(matcher.group());
            String substr = sb.toString();
           
можно  так:

           String substr = matcher.group();
            StringBuilder sb = new StringBuilder(substr);
           
2. Слова могут содержать любые цифры, в том числе и 67890.
3. Воспользуйтесь форматированием:
  System.out.println("В строке \"" + s + " подстрока  " + substr + "  является палиндромом.");
  System.out.println("В строке \"" + s + " подстрока  " + substr + "  не является палиндромом.");

**Comment by ltolok** [comment]
Исправила.
