### ISSUE TITLE
Lesson 14

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#24]
1. Запятую не надо указывать несколько раз.
String regex = "[^:,;,;.,$,_,\\s]+"; 
2. Вместо 

          if (minLength > matcher.group().length()) {
                minLength = matcher.group().length();
                strMinLengh = matcher.group();
            }

лучше

           String str = matcher.group();
            if (minLength > str.length()) {
                minLength = str.length();
                strMinLengh = str;
            }

3. strMinLengh можно сделать локальной переменной.
4. В sout используйте форматирование строк.
5. В задании сказано: Найти слово, в котором число **различных** символов минимально.

**Comment by ltolok** [comment]
Исправила.

**Comment by milkina** [comment]
Вроде правильно.
Вынесите подсчет количества символов в отдельный метод.

**Comment by ltolok** [comment]
проверьте, пжл

**Comment by milkina** [comment]
1. Отформатируйте. (Было же отформатировано).
2.  Метод numberChar сделайте статическим и добавьте модификатор доступа.

**Comment by ltolok** [comment]
ок
