### ISSUE TITLE
Lesson 16. Task 2. HeavyBoxDemo2

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#26]
Вместо 

`  TreeSet<HeavyBox> heavyBoxes = new TreeSet();`

принято писать:

`  Set<HeavyBox> heavyBoxes = new TreeSet<>();`

**Comment by ltolok** [comment]
ок

**Comment by milkina** [comment]
Забыли угловые скобки после TreeSet. ?

**Comment by ltolok** [comment]
ok
