### ISSUE TITLE
Lesson 12. Seasons

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#27]
1.   Убрать ненужную пустую строку

   public int getTemperatire() {
        return temperatire;

    }

2.  temperatire - Ошибка в слове.
3. Переименовать favoritseason в favoritSeason. и printfavoritseason в printFavoritSeason

**Comment by milkina** [comment]
Пункты 2, 3 не выполнены. И Seasons неотформатирован.

**Comment by ltolok** [comment]
Исправила. Выгрузила.
