### ISSUE TITLE
Lesson 16. Task 4.

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#28]
1. Добавьте модификатор доступа конструктору  класса Product.
2. Добавьте equals и hashCode классу Product.
3.  private String nameCategory; - лучше просто   private String name. И так понятно, что это имя каталога.
4. Добавьте equals, hashCode, toString  классу Catalog.
5. Вместо
  if (rating1 > rating2) {
                    return 1;
                } else if (rating1 < rating2) {
                    return -1;
                } else {
                    return 0;
                }
можно 
return rating1 - rating2;

6.  for (Product i : products)  - переименуйте i в product.

**Comment by ltolok** [comment]
Исправила.

**Comment by milkina** [comment]
Компаратор для price тоже исправьте.

**Comment by ltolok** [comment]
Готово.
