### ISSUE TITLE
HashMapDemo

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#34]
1. При переборе ключей и entry выводите еще и значение.
2. Вінести каждій перебор в отдельній метод.

**Comment by ltolok** [comment]
Исправила.

2017-11-24 12:40 GMT+03:00 milkina <notifications@github.com>:

**Comment by milkina** [comment]
Done, но
1. Добавить модиф. доступа для методов.

**Comment by ltolok** [comment]
Добавила.
