### ISSUE TITLE
Animal

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#36]
1.  Желательно переопределять в создаваемом классе методы toString, equals и hashCode.
2.  Animal - makeNoise(),eat() ,sleep - выведите на консоль что животное делает. Или сделайте их абстракнтіми
3. Vet.treatAnimal - вместо  System.out.println("На приеме у ветеринара   " + animal.toString());
лучше  System.out.println("На приеме у ветеринара   " + animal);
4. Добавьте мод. доступа методу  Vet.treatAnimal

**Comment by ltolok** [comment]
Исправила.

2017-11-24 12:47 GMT+03:00 milkina <notifications@github.com>:

**Comment by milkina** [comment]
1. Animal - отформатировать, добавить  equals и hashCode.

**Comment by ltolok** [comment]
Исправила
