### ISSUE TITLE
Pet

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#38]
1. Pet- перенесите метод setName за конструктор.
 В классе рекомендуется сначала объявляются статические переменные, переменные класса, потом конструкторы, геттеры, сеттеры. Потом все остальные методы.

2. PetDemo - не очень нравятся имена map1, map2, map3. Это же отдельные животные, а не Map.
3. После iterateKeys убрать ненужные переводы строки.

**Comment by ltolok** [comment]
Исправила.
