### ISSUE TITLE
Fruit

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#39]
Fruit
1. weight - поменять мод. доступа на private
2. printManufacturerInfo должен быть завершенным.

Все классы - 
1. Неотформатировано
2. Добавить equals, hashCode

**Comment by ltolok** [comment]
Исправлено.

**Comment by milkina** [comment]
1. printManufacturerInfo - вернуть мод. доступа.
2. 
 public double fruitCosts() {
        double costs = 0;
        return costs;
    }
лучше
 public double fruitCosts() {
        return 0;
    }

**Comment by ltolok** [comment]
исправила

2017-12-03 21:36 GMT+03:00 milkina <notifications@github.com>:
