### ISSUE TITLE
Lesson 10. Task 2. Shape

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#6]
1. String color в класса Shape сделать private. Создать для нее геттер и сеттер. В остальных классах то же самое.
2. Конструктор класса Shape, Circle, Rectangle сделать public.
3. Убрать ";"  после конструктора в класса Shape и после метода draw в Circle.
4. Убрать метод main из класса Shape.
5. Добавить в конструктор классов Circle, Rectangle параметр для инициализации цвета.
6. В Rectangle  не нужна переменная класса  String shape[];
7. Добавить в draw еще и цвет.
8. Убрать комментарии из класса Rectangle.

**Comment by ltolok** [comment]
Исправила.

**Comment by milkina** [comment]
Done
