### ISSUE TITLE
Lesson 9. Car

### ISSUE THREAD

**Issue by milkina** [ltolok/projectproject#8]
1. Engine - убрать ненужный импорт.
2. Все переменные классов должны быть  private.
3. Убрать ненужные пустые строки и ";"
4. Из класса Driver, Lorry, SportCar можно убрать конструктор - он и так добавиться компилятором.
5. Переименуйте метод  getCarrying() в getSpeed()

**Comment by milkina** [comment]
Пункт 4 не выполнен.

**Comment by ltolok** [comment]
Конструктор убрала из Driver, Lorry, SportCar.

**Comment by milkina** [comment]
Done.
